//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iiii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int Restaurantid { get; set; }
        public string Restaurantname { get; set; }
        public string Menu_name { get; set; }
        public string price { get; set; }
        public string Image_menu { get; set; }
    
        public virtual restaurant restaurant { get; set; }
    }
}
