//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iiii.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public restaurant()
        {
            this.bookings = new HashSet<booking>();
            this.menus = new HashSet<menu>();
        }
    
        public int Restaurant_id { get; set; }
        public string Restaurant_name { get; set; }
        public string Restaurant_type { get; set; }
        public string Restaurant_address { get; set; }
        public string Restaurant_about { get; set; }
        public int Restaurant_phone { get; set; }
        public System.TimeSpan OpenTime { get; set; }
        public System.TimeSpan closetime { get; set; }
        public string image1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<menu> menus { get; set; }
    }
}
